<?php
return [

    'SIP' => [
        "Wawasan Kebangsaan",
        "Etika dan Kode Etik Profesi Polri",
        "Peraturan Pemerintah Nomor 1, 2, dan 3 Tahun 2003",
        "Nilai Sejarah Polri",
        "Integritas dan Budaya Anti Korupsi",
        "Hukum Pidana dan Hukum Acara Pidana",
        "Pengetahuan Tentang HAM",
        "Diskresi & Restorative Justice",
        "PPA dan ABH",
        "Manajemen Training Level I",
        "Kepemimpinan",
        "Sistem, Manajemen dan Standar Keberhasilan Operasional Kepolisian",
        "Sistem Pelayanan Kepolisian Terpadu",
        "Manajemen Fungsi Intelkam",
        "Manajemen Fungsi Binmas",
        "Manajemen Fungsi Sabhara",
        "Manajemen Fungsi Lantas",
        "Manajemen Fungsi Reserse",
        "Perencanaan dan Penganggaran Polri",
        "Manajemen SDM Polri",
        "Manajemen Logistik Polri",
        "Keuangan Polri",
        "Manajemen Tingkat Polsek",
        "Community Policing",
        "Democratic Policing",
        "Predictive Policing",
        "Pengetahuan Sosial",
        "Pelayanan Prima",
        "Manajemen Penanggulangan Bencana",
        "Search and Rescue (SAR)",
        "Identifikasi Kepolisian",
        "Laboratorium Forensik Kedokteran Kepolisian",
        "Tata Naskah Dinas di Lingkungan Polri",
        "Tata Upacara dan Pedang Perwira",
        "Penggunaan Senjata Api dan Menembak",
        "Teknik Keselamatan dan Bela Diri Polri",
        "Sistem Pelayanan Polri Berbasis Elektronik",
        "Psikologi Sosial dan Teknik Dasar Konseling",
        "Manajemen Kehumasan Polri",
        "Teknologi Informasi Kepolisian",
        "Pencegahan Kejahatan (Crime Prevention)",
        "Gladi Wirottama",
        "Porismas",
        "Latihan Teknis/Latihan Kerja",
        "Ujian Kompetensi Perwira Pertama",
    ],

    'PAG' => [
        "Pancasila dan Wawasan Kebangsaan",
        "Etika dan Kode Etik Profesi Polri",
        "Integritas dan Budaya Anti Korupsi",
        "Peraturan Pemerintah Nomor 1, 2, dan 3 tahun 2003",
        "Hukum Pidana dan Hukum Acara Pidana",
        "Diskresi Kepolisian dan Restorative Justice",
        "Hak Asasi Manusia (HAM)",
        "PPA dan ABH",
        "Kepemimpinan",
        "Manajemen Pembinaan Polri",
        "Manajemen Tingkat Polsek",
        "Manajemen Training Level I",
        "Sistem, Manajemen dan Standar Keberhasilan Operasional Polri",
        "Tata Naskah Dinas di Lingkungan Polri",
        "Tata Upacara dan Pedang Perwira",
        "Pencegahan Kejahatan (Crime Prevention)",
        "Manajemen Kehumasan Polri",
        "Latihan Teknis",
    ],

];
